/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamedica;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author super
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bntLogin = new javax.swing.JButton();
        bntCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        senhaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chxMedico = new javax.swing.JCheckBox();
        chxPaciente = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMaximumSize(new java.awt.Dimension(780, 780));
        setMinimumSize(new java.awt.Dimension(780, 780));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("BEM-VINDO AO SISTEMA DE AGENDAMENTO MEDICO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 430, 70);

        bntLogin.setText("LOGIN");
        bntLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bntLogin);
        bntLogin.setBounds(540, 120, 72, 23);

        bntCadastrar.setForeground(new java.awt.Color(0, 153, 255));
        bntCadastrar.setText("Cadastrar-se");
        bntCadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bntCadastrar.setBorderPainted(false);
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bntCadastrar);
        bntCadastrar.setBounds(390, 700, 130, 18);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 100, 49, 16);

        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 140, 135, 16);
        getContentPane().add(nomeTxt);
        nomeTxt.setBounds(290, 100, 211, 22);
        getContentPane().add(senhaTxt);
        senhaTxt.setBounds(290, 140, 211, 22);

        jLabel4.setText("Voce esta logando como:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 180, 170, 16);

        chxMedico.setText("Medico");
        getContentPane().add(chxMedico);
        chxMedico.setBounds(290, 180, 85, 20);

        chxPaciente.setText("Paciente");
        getContentPane().add(chxPaciente);
        chxPaciente.setBounds(420, 180, 85, 20);

        jLabel6.setText("Ainda não possui conta?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 700, 240, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cadastro_inicial(1).png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(662, 666));
        jLabel5.setMinimumSize(new java.awt.Dimension(662, 666));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-60, -80, 840, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
        // TODO add your handling code here:
        CadastrarPessoa frame = new CadastrarPessoa();
        frame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void bntLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLoginActionPerformed
        // TODO add your handling code here:
        try{
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String json= String.join(" ",Files.readAllLines(Paths.get("pacientes.json"),StandardCharsets.UTF_8));
        String json2= String.join(" ",Files.readAllLines(Paths.get("medicos.json"),StandardCharsets.UTF_8));
        java.lang.reflect.Type listTypePaciente = new TypeToken <ArrayList<Paciente>>(){}.getType();
        ArrayList<Paciente> pacientes = gson.fromJson(json,listTypePaciente);
        java.lang.reflect.Type listTypeMedico = new TypeToken <ArrayList<Medico>>(){}.getType();
        ArrayList<Medico> medicos = gson.fromJson(json2, listTypeMedico);
        //Caso login medico
        if(chxMedico.isSelected()==true&&chxPaciente.isSelected()==false){
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            boolean verificador = false;
            for(Medico medico : medicos){
                if(medico.getNome().equals(nome)&&medico.getSenha().equals(senha)){
                    verificador=true;
                    Writer writer = new FileWriter("usuario.json");
                    gson.toJson(medico,writer);
                    writer.flush();
                    writer.close();
                    PosLogin frame = new PosLogin();
                    
                    System.out.println("medico");

                    frame.setVisible(true);
                    //this.disable();
                    continue;
                }
           
            }
            if(verificador==false){
                JOptionPane.showMessageDialog(null, "Login Invalido, Cadastre-se ou cheque se o nome e senha estao corretos","ERRO", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        //Caso login paciente
        if(chxMedico.isSelected()==false&&chxPaciente.isSelected()==true){
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            boolean verificador = false;
            for(Paciente paciente:pacientes){
                if(paciente.getNome().equals(nome)&&paciente.getSenha().equals(senha)){
                    verificador=true;
                    Writer writer = new FileWriter("usuario.json");
                    gson.toJson(paciente,writer);
                    writer.flush();
                    writer.close();
                    PosLogin frame = new PosLogin();
                    
                    System.out.println("paciente");
                    
                    frame.setVisible(true);
                    //this.disable();
                    continue;
                }
            }
            if(verificador==false){
                JOptionPane.showMessageDialog(null, "Login Invalido, Cadastre-se ou cheque se o nome e senha estao corretos","ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Caso erro
        if((chxMedico.isSelected()==true&&chxPaciente.isSelected()==true)||(chxMedico.isSelected()==false&&chxPaciente.isSelected()==false)){
            JOptionPane.showMessageDialog(null, "Ola, o Login nao deu certo! Voce deixou ambas opcoes ativas ou inativas","ERRO", JOptionPane.ERROR_MESSAGE);
        }
        }catch (IOException ex) {
            Logger.getLogger(CadastrarPessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton bntLogin;
    private javax.swing.JCheckBox chxMedico;
    private javax.swing.JCheckBox chxPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField senhaTxt;
    // End of variables declaration//GEN-END:variables
}
