/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamedica;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author super
 */
public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JTextField();
        chxMedico = new javax.swing.JCheckBox();
        chxPaciente = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbMedico = new javax.swing.JComboBox<>();
        jcbPaciente = new javax.swing.JComboBox<>();
        nTxt = new javax.swing.JTextField();
        sTxt = new javax.swing.JTextField();
        iTxt = new javax.swing.JTextField();
        lblNomeNovo = new javax.swing.JLabel();
        lblSenhaNova = new javax.swing.JLabel();
        lblIdadeNova = new javax.swing.JLabel();
        lblEspecialidadeNova = new javax.swing.JLabel();
        eTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE EDICAO DE USUARIO");
        setMaximumSize(new java.awt.Dimension(750, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("EDITAR USUARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 0, 214, 38);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(88, 436, 72, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(201, 436, 76, 23);

        jLabel2.setText("Para editar o usuario voce deve digitar novamente o login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 40, 311, 28);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 80, 72, 16);
        getContentPane().add(nomeTxt);
        nomeTxt.setBounds(380, 80, 212, 22);

        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 120, 52, 16);
        getContentPane().add(senhaTxt);
        senhaTxt.setBounds(380, 120, 212, 22);

        chxMedico.setText("Medico");
        chxMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(chxMedico);
        chxMedico.setBounds(410, 160, 85, 20);

        chxPaciente.setText("Paciente");
        chxPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(chxPaciente);
        chxPaciente.setBounds(540, 160, 85, 20);

        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 160, 52, 16);

        jLabel6.setText("O que deseja editar?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(88, 207, 122, 16);

        jcbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Especialidade", "Senha" }));
        jcbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbMedico);
        jcbMedico.setBounds(216, 204, 488, 22);

        jcbPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Idade", "Senha" }));
        jcbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jcbPaciente);
        jcbPaciente.setBounds(216, 238, 488, 22);
        getContentPane().add(nTxt);
        nTxt.setBounds(216, 272, 488, 22);
        getContentPane().add(sTxt);
        sTxt.setBounds(216, 306, 488, 22);
        getContentPane().add(iTxt);
        iTxt.setBounds(216, 340, 488, 22);

        lblNomeNovo.setText("Nome Novo:");
        getContentPane().add(lblNomeNovo);
        lblNomeNovo.setBounds(88, 275, 109, 16);

        lblSenhaNova.setText("Senha Nova:");
        getContentPane().add(lblSenhaNova);
        lblSenhaNova.setBounds(88, 309, 96, 16);

        lblIdadeNova.setText("Idade Nova:");
        getContentPane().add(lblIdadeNova);
        lblIdadeNova.setBounds(88, 343, 107, 16);

        lblEspecialidadeNova.setText("Especialidade Nova:");
        getContentPane().add(lblEspecialidadeNova);
        lblEspecialidadeNova.setBounds(88, 377, 107, 16);
        getContentPane().add(eTxt);
        eTxt.setBounds(216, 374, 488, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/blackkk.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 740, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PosLogin frame = new PosLogin();
        frame.setVisible(true);
        this.disable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        try{
        
        String json= String.join(" ",Files.readAllLines(Paths.get("pacientes.json"),StandardCharsets.UTF_8));
        String json2= String.join(" ",Files.readAllLines(Paths.get("medicos.json"),StandardCharsets.UTF_8));
        java.lang.reflect.Type listTypePaciente = new TypeToken <ArrayList<Paciente>>(){}.getType();
        ArrayList<Paciente> pacientes = gson.fromJson(json,listTypePaciente);
        java.lang.reflect.Type listTypeMedico = new TypeToken <ArrayList<Medico>>(){}.getType();
        ArrayList<Medico> medicos = gson.fromJson(json2, listTypeMedico);
        //Caso login medico
        if(chxMedico.isSelected()==true&&chxPaciente.isSelected()==false){
            jcbMedico.setVisible(true);
            jcbPaciente.setVisible(false);
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            boolean verificador = false;
            int index=0;
            for(Medico medico : medicos){
                if(medico.getNome().equals(nome)&&medico.getSenha().equals(senha)){
                    verificador=true;
                    String nomeNovo = "";
                    String especialidadeNova="";
                    String senhaNova="";
                    if(jcbMedico.getModel().getSelectedItem().equals("Especialidade")){
                        especialidadeNova = eTxt.getText();
                        medicos.remove(index);
                        medico.setEspecialidade(especialidadeNova);
                        medicos.add(medico);
                    }
                    
                    if(jcbMedico.getModel().getSelectedItem().equals("Nome")){
                        nomeNovo = nTxt.getText().toUpperCase();
                        medicos.remove(index);
                        medico.setNome(nomeNovo);
                        medicos.add(medico);
                    }
                    if(jcbMedico.getModel().getSelectedItem().equals("Senha")){
                        senhaNova=sTxt.getText();
                        medicos.remove(index);
                        medico.setSenha(senhaNova);
                        medicos.add(medico);
                    }
                    try (Writer writer = new FileWriter("medicos.json")) {
                    String jsonNovo = gson.toJson(medicos);
                    gson.toJson(medicos,writer);
                    writer.flush();
                    writer.close();
                    }
                    Writer writer = null;
        try{
            writer = new FileWriter("usuario.json");
            gson.toJson(medico,writer);
            writer.flush();
            writer.close();
        }catch(Exception e){
            e.getMessage();
        }
                    JOptionPane.showMessageDialog(null, "Ola, a edicao deu certo!"); 
                    this.dispose();
                    continue;
                    
                    
                }
                index=index+1;
           
            }
            if(verificador==false){
                JOptionPane.showMessageDialog(null, "Nao foi possivel editar, cheque se o nome e senha estao corretos","ERRO", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        //Caso login paciente
        if(chxMedico.isSelected()==false&&chxPaciente.isSelected()==true){
            jcbMedico.setVisible(false);
            jcbPaciente.setVisible(true);
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            boolean verificador = false;
            int index=0;
            for(Paciente paciente:pacientes){
                if(paciente.getNome().equals(nome)&&paciente.getSenha().equals(senha)){
                    verificador=true;
                    String nomeNovo = "";
                    String idadeNova="";
                    String senhaNova="";
                    if(jcbPaciente.getModel().getSelectedItem().equals("Idade")){
                        idadeNova = iTxt.getText();
                        pacientes.remove(index);
                        paciente.setIdade(idadeNova);
                        pacientes.add(paciente);
                    }
                    if(jcbPaciente.getModel().getSelectedItem().equals("Nome")){
                        nomeNovo = nTxt.getText().toUpperCase();
                        pacientes.remove(index);
                        paciente.setNome(nomeNovo);
                        pacientes.add(paciente);
                    }
                    if(jcbPaciente.getModel().getSelectedItem().equals("Senha")){
                        senhaNova=sTxt.getText();
                        pacientes.remove(index);
                        paciente.setSenha(senhaNova);
                        pacientes.add(paciente);
                    }
                    try (Writer writer = new FileWriter("pacientes.json")) {
                    gson.toJson(pacientes,writer);
                    writer.flush();
                    writer.close();
                    }
                    Writer writer = null;
        try{
            writer = new FileWriter("usuario.json");
            gson.toJson(paciente,writer);
            writer.flush();
            writer.close();
        }catch(Exception e){
            e.getMessage();
        }
                    JOptionPane.showMessageDialog(null, "Ola, a edicao deu certo!"); 
                    this.dispose();
                    continue;
                    
                }
                index=index+1;
            }
            if(verificador==false){
                JOptionPane.showMessageDialog(null, "Nao foi possivel editar, cheque se o nome e senha estao corretos","ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Caso erro
        if((chxMedico.isSelected()==true&&chxPaciente.isSelected()==true)||(chxMedico.isSelected()==false&&chxPaciente.isSelected()==false)){
            JOptionPane.showMessageDialog(null, "Ola, a Edicao nao deu certo! Voce deixou ambas opcoes ativas ou inativas","ERRO", JOptionPane.ERROR_MESSAGE);
        }
        }catch (IOException ex) {
            Logger.getLogger(CadastrarPessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jcbMedico.setVisible(false);
        jcbPaciente.setVisible(false);
        lblNomeNovo.setVisible(false);
        lblEspecialidadeNova.setVisible(false);
        lblSenhaNova.setVisible(false);
        lblIdadeNova.setVisible(false);
        iTxt.setVisible(false);
        eTxt.setVisible(false);
        nTxt.setVisible(false);
        sTxt.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void chxMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxMedicoActionPerformed
        // TODO add your handling code here:
        if(chxMedico.isSelected()==true&&chxPaciente.isSelected()==false){
            jcbMedico.setVisible(true);
            jcbPaciente.setVisible(false);
        }else{
            jcbMedico.setVisible(false);
            jcbPaciente.setVisible(false);
            jcbMedico.setVisible(false);
        jcbPaciente.setVisible(false);
        lblNomeNovo.setVisible(false);
        lblEspecialidadeNova.setVisible(false);
        lblSenhaNova.setVisible(false);
        lblIdadeNova.setVisible(false);
        iTxt.setVisible(false);
        eTxt.setVisible(false);
        nTxt.setVisible(false);
        sTxt.setVisible(false);
        }
    }//GEN-LAST:event_chxMedicoActionPerformed

    private void chxPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxPacienteActionPerformed
        // TODO add your handling code here:
        if(chxMedico.isSelected()==false&&chxPaciente.isSelected()==true){
            jcbMedico.setVisible(false);
            jcbPaciente.setVisible(true);
        }else{
            jcbMedico.setVisible(false);
            jcbPaciente.setVisible(false);
            jcbMedico.setVisible(false);
        jcbPaciente.setVisible(false);
        lblNomeNovo.setVisible(false);
        lblEspecialidadeNova.setVisible(false);
        lblSenhaNova.setVisible(false);
        lblIdadeNova.setVisible(false);
        iTxt.setVisible(false);
        eTxt.setVisible(false);
        nTxt.setVisible(false);
        sTxt.setVisible(false);
        }
    }//GEN-LAST:event_chxPacienteActionPerformed

    private void jcbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMedicoActionPerformed
        // TODO add your handling code here:
        if(jcbMedico.getModel().getSelectedItem().equals("Especialidade")){
            lblEspecialidadeNova.setVisible(true);
            eTxt.setVisible(true);
        }
        else{
            lblEspecialidadeNova.setVisible(false);
            eTxt.setVisible(false);
        }
        if(jcbMedico.getModel().getSelectedItem().equals("Nome")){
            lblNomeNovo.setVisible(true);
            nTxt.setVisible(true);
        }
        else{
            lblNomeNovo.setVisible(false);
            nTxt.setVisible(false);
        }
        if(jcbMedico.getModel().getSelectedItem().equals("Senha")){
            lblSenhaNova.setVisible(true);
            sTxt.setVisible(true);            
        }
        else{
            lblSenhaNova.setVisible(false);
            sTxt.setVisible(false);
        }
    }//GEN-LAST:event_jcbMedicoActionPerformed

    private void jcbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPacienteActionPerformed
        // TODO add your handling code here:
        if(jcbPaciente.getModel().getSelectedItem().equals("Idade")){
            lblIdadeNova.setVisible(true);
            iTxt.setVisible(true);
        }
        else{
            lblIdadeNova.setVisible(false);
            iTxt.setVisible(false);
        }
        if(jcbPaciente.getModel().getSelectedItem().equals("Nome")){
            lblNomeNovo.setVisible(true);
            nTxt.setVisible(true);
        }
        else{
            lblNomeNovo.setVisible(false);
            nTxt.setVisible(false);
        }
        if(jcbPaciente.getModel().getSelectedItem().equals("Senha")){
            lblSenhaNova.setVisible(true);
            sTxt.setVisible(true);            
        }
        else{
            lblSenhaNova.setVisible(false);
            sTxt.setVisible(false);
        }
    }//GEN-LAST:event_jcbPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chxMedico;
    private javax.swing.JCheckBox chxPaciente;
    private javax.swing.JTextField eTxt;
    private javax.swing.JTextField iTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcbMedico;
    private javax.swing.JComboBox<String> jcbPaciente;
    private javax.swing.JLabel lblEspecialidadeNova;
    private javax.swing.JLabel lblIdadeNova;
    private javax.swing.JLabel lblNomeNovo;
    private javax.swing.JLabel lblSenhaNova;
    private javax.swing.JTextField nTxt;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField sTxt;
    private javax.swing.JTextField senhaTxt;
    // End of variables declaration//GEN-END:variables
}
